linters:
  enable-all: true
  disable:
    - nlreturn
    - exhaustivestruct
    - godox

linters-settings:
  cyclop:
    max-complexity: 15 # minimal code complexity to report, go-report-card uses 15.
  gomoddirectives:
    replace-allow-list:
      - k8s.io/client-go # Kubernetes client specific issue. See https://maelvls.dev/client-go-transitive-hell/.